// Code generated by stanc v2.37.0
#include <stan/model/model_header.hpp>
namespace model_binary_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 89> locations_array__ =
  {" (found before start of program)",
  " (in 'src/stan/model_binary.stan', line 63, column 3 to column 22)",
  " (in 'src/stan/model_binary.stan', line 64, column 3 to column 24)",
  " (in 'src/stan/model_binary.stan', line 66, column 3 to column 32)",
  " (in 'src/stan/model_binary.stan', line 67, column 3 to column 33)",
  " (in 'src/stan/model_binary.stan', line 71, column 3 to column 30)",
  " (in 'src/stan/model_binary.stan', line 73, column 8 to column 58)",
  " (in 'src/stan/model_binary.stan', line 72, column 3 to line 73, column 58)",
  " (in 'src/stan/model_binary.stan', line 77, column 8 to column 92)",
  " (in 'src/stan/model_binary.stan', line 78, column 8 to column 87)",
  " (in 'src/stan/model_binary.stan', line 81, column 12 to column 93)",
  " (in 'src/stan/model_binary.stan', line 80, column 8 to line 81, column 93)",
  " (in 'src/stan/model_binary.stan', line 85, column 12 to column 60)",
  " (in 'src/stan/model_binary.stan', line 84, column 8 to line 85, column 60)",
  " (in 'src/stan/model_binary.stan', line 76, column 4 to line 86, column 5)",
  " (in 'src/stan/model_binary.stan', line 90, column 19 to column 24)",
  " (in 'src/stan/model_binary.stan', line 90, column 12 to column 33)",
  " (in 'src/stan/model_binary.stan', line 91, column 19 to column 29)",
  " (in 'src/stan/model_binary.stan', line 91, column 12 to column 39)",
  " (in 'src/stan/model_binary.stan', line 94, column 12 to line 96, column 41)",
  " (in 'src/stan/model_binary.stan', line 99, column 12 to column 42)",
  " (in 'src/stan/model_binary.stan', line 100, column 12 to column 58)",
  " (in 'src/stan/model_binary.stan', line 103, column 12 to column 85)",
  " (in 'src/stan/model_binary.stan', line 89, column 26 to line 104, column 9)",
  " (in 'src/stan/model_binary.stan', line 89, column 8 to line 104, column 9)",
  " (in 'src/stan/model_binary.stan', line 88, column 4 to line 105, column 5)",
  " (in 'src/stan/model_binary.stan', line 24, column 4 to column 19)",
  " (in 'src/stan/model_binary.stan', line 27, column 4 to column 19)",
  " (in 'src/stan/model_binary.stan', line 28, column 4 to column 19)",
  " (in 'src/stan/model_binary.stan', line 30, column 4 to column 23)",
  " (in 'src/stan/model_binary.stan', line 31, column 4 to column 22)",
  " (in 'src/stan/model_binary.stan', line 32, column 4 to column 22)",
  " (in 'src/stan/model_binary.stan', line 34, column 10 to column 15)",
  " (in 'src/stan/model_binary.stan', line 34, column 4 to column 42)",
  " (in 'src/stan/model_binary.stan', line 36, column 10 to column 15)",
  " (in 'src/stan/model_binary.stan', line 36, column 17 to column 18)",
  " (in 'src/stan/model_binary.stan', line 36, column 4 to column 44)",
  " (in 'src/stan/model_binary.stan', line 38, column 11 to column 16)",
  " (in 'src/stan/model_binary.stan', line 38, column 18 to column 21)",
  " (in 'src/stan/model_binary.stan', line 38, column 4 to column 25)",
  " (in 'src/stan/model_binary.stan', line 39, column 11 to column 16)",
  " (in 'src/stan/model_binary.stan', line 39, column 18 to column 22)",
  " (in 'src/stan/model_binary.stan', line 39, column 4 to column 26)",
  " (in 'src/stan/model_binary.stan', line 40, column 11 to column 16)",
  " (in 'src/stan/model_binary.stan', line 40, column 18 to column 22)",
  " (in 'src/stan/model_binary.stan', line 40, column 4 to column 26)",
  " (in 'src/stan/model_binary.stan', line 44, column 4 to column 32)",
  " (in 'src/stan/model_binary.stan', line 45, column 4 to column 18)",
  " (in 'src/stan/model_binary.stan', line 46, column 4 to column 29)",
  " (in 'src/stan/model_binary.stan', line 47, column 4 to column 26)",
  " (in 'src/stan/model_binary.stan', line 49, column 4 to column 31)",
  " (in 'src/stan/model_binary.stan', line 50, column 4 to column 17)",
  " (in 'src/stan/model_binary.stan', line 51, column 4 to column 28)",
  " (in 'src/stan/model_binary.stan', line 52, column 4 to column 25)",
  " (in 'src/stan/model_binary.stan', line 54, column 4 to column 30)",
  " (in 'src/stan/model_binary.stan', line 55, column 4 to column 16)",
  " (in 'src/stan/model_binary.stan', line 56, column 4 to column 27)",
  " (in 'src/stan/model_binary.stan', line 57, column 4 to column 24)",
  " (in 'src/stan/model_binary.stan', line 60, column 10 to column 15)",
  " (in 'src/stan/model_binary.stan', line 60, column 17 to column 27)",
  " (in 'src/stan/model_binary.stan', line 60, column 3 to column 55)",
  " (in 'src/stan/model_binary.stan', line 63, column 10 to column 13)",
  " (in 'src/stan/model_binary.stan', line 63, column 15 to column 16)",
  " (in 'src/stan/model_binary.stan', line 64, column 10 to column 14)",
  " (in 'src/stan/model_binary.stan', line 64, column 16 to column 17)",
  " (in 'src/stan/model_binary.stan', line 66, column 9 to column 10)",
  " (in 'src/stan/model_binary.stan', line 66, column 19 to column 20)",
  " (in 'src/stan/model_binary.stan', line 66, column 22 to column 26)",
  " (in 'src/stan/model_binary.stan', line 67, column 19 to column 20)",
  " (in 'src/stan/model_binary.stan', line 67, column 22 to column 26)",
  " (in 'src/stan/model_binary.stan', line 71, column 9 to column 10)",
  " (in 'src/stan/model_binary.stan', line 71, column 19 to column 20)",
  " (in 'src/stan/model_binary.stan', line 71, column 22 to column 26)",
  " (in 'src/stan/model_binary.stan', line 9, column 22 to column 57)",
  " (in 'src/stan/model_binary.stan', line 9, column 8 to column 57)",
  " (in 'src/stan/model_binary.stan', line 10, column 22 to column 64)",
  " (in 'src/stan/model_binary.stan', line 10, column 8 to column 64)",
  " (in 'src/stan/model_binary.stan', line 11, column 22 to column 57)",
  " (in 'src/stan/model_binary.stan', line 11, column 8 to column 57)",
  " (in 'src/stan/model_binary.stan', line 12, column 8 to column 50)",
  " (in 'src/stan/model_binary.stan', line 8, column 69 to line 13, column 5)",
  " (in 'src/stan/model_binary.stan', line 16, column 22 to column 98)",
  " (in 'src/stan/model_binary.stan', line 16, column 8 to column 98)",
  " (in 'src/stan/model_binary.stan', line 17, column 22 to column 112)",
  " (in 'src/stan/model_binary.stan', line 17, column 8 to column 112)",
  " (in 'src/stan/model_binary.stan', line 18, column 22 to column 98)",
  " (in 'src/stan/model_binary.stan', line 18, column 8 to column 98)",
  " (in 'src/stan/model_binary.stan', line 19, column 8 to column 50)",
  " (in 'src/stan/model_binary.stan', line 15, column 74 to line 20, column 4)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T2__>>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T4__>>>>* = nullptr>
stan::return_type_t<stan::base_type_t<T0__>, T2__, T3__, T4__>
set_prior(const T0__& x_arg__, const T1__& fam, const T2__& loc, const T3__&
          scale, const T4__& df, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T2__>>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T4__>>>>* = nullptr>
stan::return_type_t<stan::base_type_t<T0__>, T2__, T3__, T4__>
set_half_prior(const T0__& x_arg__, const T1__& fam, const T2__& loc,
               const T3__& scale, const T4__& df, std::ostream* pstream__);
// real set_prior(vector, int, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T2__>>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T4__>>>>*>
stan::return_type_t<stan::base_type_t<T0__>, T2__, T3__, T4__>
set_prior(const T0__& x_arg__, const T1__& fam, const T2__& loc, const T3__&
          scale, const T4__& df, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>, T2__,
                             T3__, T4__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 74;
    if (stan::math::logical_eq(fam, 1)) {
      current_statement__ = 73;
      return stan::math::normal_lpdf<false>(x, loc, scale);
    }
    current_statement__ = 76;
    if (stan::math::logical_eq(fam, 2)) {
      current_statement__ = 75;
      return stan::math::student_t_lpdf<false>(x, df, loc, scale);
    }
    current_statement__ = 78;
    if (stan::math::logical_eq(fam, 3)) {
      current_statement__ = 77;
      return stan::math::cauchy_lpdf<false>(x, loc, scale);
    }
    current_statement__ = 79;
    {
      std::stringstream errmsg_stream__;
      stan::math::stan_print(&errmsg_stream__, "Unknown prior family code:");
      stan::math::stan_print(&errmsg_stream__, fam);
      throw std::domain_error(errmsg_stream__.str());
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real set_half_prior(vector, int, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T2__>>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              stan::math::disjunction<stan::is_autodiff<T4__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T4__>>>>*>
stan::return_type_t<stan::base_type_t<T0__>, T2__, T3__, T4__>
set_half_prior(const T0__& x_arg__, const T1__& fam, const T2__& loc,
               const T3__& scale, const T4__& df, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>, T2__,
                             T3__, T4__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 82;
    if (stan::math::logical_eq(fam, 1)) {
      current_statement__ = 81;
      return (stan::math::normal_lpdf<false>(x, loc, scale) -
             (stan::math::rows(x) * stan::math::normal_lccdf(0, loc, scale)));
    }
    current_statement__ = 84;
    if (stan::math::logical_eq(fam, 2)) {
      current_statement__ = 83;
      return (stan::math::student_t_lpdf<false>(x, df, loc, scale) -
             (stan::math::rows(x) *
             stan::math::student_t_lccdf(0, df, loc, scale)));
    }
    current_statement__ = 86;
    if (stan::math::logical_eq(fam, 3)) {
      current_statement__ = 85;
      return (stan::math::cauchy_lpdf<false>(x, loc, scale) -
             (stan::math::rows(x) * stan::math::cauchy_lccdf(0, loc, scale)));
    }
    current_statement__ = 87;
    {
      std::stringstream errmsg_stream__;
      stan::math::stan_print(&errmsg_stream__, "Unknown prior family code:");
      stan::math::stan_print(&errmsg_stream__, fam);
      throw std::domain_error(errmsg_stream__.str());
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class model_binary_model final : public model_base_crtp<model_binary_model> {
 private:
  int p;
  int J;
  int K;
  int n_obs;
  int n_fe;
  int n_re;
  std::vector<int> id;
  std::vector<std::vector<int>> Y;
  Eigen::Matrix<double,-1,-1> B_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> Z_data__;
  int prior_beta_fam;
  double beta_loc;
  double beta_scale;
  double beta_df;
  int prior_phi_fam;
  double phi_loc;
  double phi_scale;
  double phi_df;
  int prior_sd_fam;
  double sd_loc;
  double sd_scale;
  double sd_df;
  Eigen::Matrix<double,-1,-1> X_fixed_data__;
  int phi_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> B{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_fixed{nullptr, 0, 0};
 public:
  ~model_binary_model() {}
  model_binary_model(stan::io::var_context& context__, unsigned int
                     random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_binary_model_namespace::model_binary_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization", "p", "int",
        std::vector<size_t>{});
      p = std::numeric_limits<int>::min();
      current_statement__ = 26;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 27;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 28;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 29;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 1);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "n_fe", "int",
        std::vector<size_t>{});
      n_fe = std::numeric_limits<int>::min();
      current_statement__ = 30;
      n_fe = context__.vals_i("n_fe")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "n_fe", n_fe, 1);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "n_re", "int",
        std::vector<size_t>{});
      n_re = std::numeric_limits<int>::min();
      current_statement__ = 31;
      n_re = context__.vals_i("n_re")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "n_re", n_re, 0);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("id", "n_obs", n_obs);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "id", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      id = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 33;
      id = context__.vals_i("id");
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "id", id, 1);
      current_statement__ = 33;
      stan::math::check_less_or_equal(function__, "id", id, J);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("Y", "n_obs", n_obs);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("Y", "p", p);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>(p)});
      Y = std::vector<std::vector<int>>(n_obs,
            std::vector<int>(p, std::numeric_limits<int>::min()));
      {
        std::vector<int> Y_flat__;
        current_statement__ = 36;
        Y_flat__ = context__.vals_i("Y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            stan::model::assign(Y, Y_flat__[(pos__ - 1)],
              "assigning variable Y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "Y", Y, 0);
      current_statement__ = 36;
      stan::math::check_less_or_equal(function__, "Y", Y, 1);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("B", "n_obs", n_obs);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("B", "p * K", (p * K));
      current_statement__ = 39;
      context__.validate_dims("data initialization", "B", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>((p * K))});
      B_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_obs, (p * K),
                   std::numeric_limits<double>::quiet_NaN());
      new (&B) Eigen::Map<Eigen::Matrix<double,-1,-1>>(B_data__.data(),
        n_obs, (p * K));
      {
        std::vector<local_scalar_t__> B_flat__;
        current_statement__ = 39;
        B_flat__ = context__.vals_r("B");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= (p * K); ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            stan::model::assign(B, B_flat__[(pos__ - 1)],
              "assigning variable B", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 40;
      stan::math::validate_non_negative_index("X", "n_obs", n_obs);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("X", "n_fe", n_fe);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>(n_fe)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_obs, n_fe,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(),
        n_obs, n_fe);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 42;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_fe; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 43;
      stan::math::validate_non_negative_index("Z", "n_obs", n_obs);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("Z", "n_re", n_re);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "Z", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>(n_re)});
      Z_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_obs, n_re,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Z) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z_data__.data(),
        n_obs, n_re);
      {
        std::vector<local_scalar_t__> Z_flat__;
        current_statement__ = 45;
        Z_flat__ = context__.vals_r("Z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            stan::model::assign(Z, Z_flat__[(pos__ - 1)],
              "assigning variable Z", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 46;
      context__.validate_dims("data initialization", "prior_beta_fam", "int",
        std::vector<size_t>{});
      prior_beta_fam = std::numeric_limits<int>::min();
      current_statement__ = 46;
      prior_beta_fam = context__.vals_i("prior_beta_fam")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "prior_beta_fam",
        prior_beta_fam, 1);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "beta_loc", "double",
        std::vector<size_t>{});
      beta_loc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 47;
      beta_loc = context__.vals_r("beta_loc")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization", "beta_scale", "double",
        std::vector<size_t>{});
      beta_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 48;
      beta_scale = context__.vals_r("beta_scale")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "beta_scale",
        beta_scale, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "beta_df", "double",
        std::vector<size_t>{});
      beta_df = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      beta_df = context__.vals_r("beta_df")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "beta_df", beta_df, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "prior_phi_fam", "int",
        std::vector<size_t>{});
      prior_phi_fam = std::numeric_limits<int>::min();
      current_statement__ = 50;
      prior_phi_fam = context__.vals_i("prior_phi_fam")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "prior_phi_fam",
        prior_phi_fam, 1);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "phi_loc", "double",
        std::vector<size_t>{});
      phi_loc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      phi_loc = context__.vals_r("phi_loc")[(1 - 1)];
      current_statement__ = 52;
      context__.validate_dims("data initialization", "phi_scale", "double",
        std::vector<size_t>{});
      phi_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 52;
      phi_scale = context__.vals_r("phi_scale")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "phi_scale", phi_scale,
        0);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "phi_df", "double",
        std::vector<size_t>{});
      phi_df = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      phi_df = context__.vals_r("phi_df")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "phi_df", phi_df, 0);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "prior_sd_fam", "int",
        std::vector<size_t>{});
      prior_sd_fam = std::numeric_limits<int>::min();
      current_statement__ = 54;
      prior_sd_fam = context__.vals_i("prior_sd_fam")[(1 - 1)];
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "prior_sd_fam",
        prior_sd_fam, 1);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "sd_loc", "double",
        std::vector<size_t>{});
      sd_loc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 55;
      sd_loc = context__.vals_r("sd_loc")[(1 - 1)];
      current_statement__ = 56;
      context__.validate_dims("data initialization", "sd_scale", "double",
        std::vector<size_t>{});
      sd_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 56;
      sd_scale = context__.vals_r("sd_scale")[(1 - 1)];
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "sd_scale", sd_scale, 0);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "sd_df", "double",
        std::vector<size_t>{});
      sd_df = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 57;
      sd_df = context__.vals_r("sd_df")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "sd_df", sd_df, 0);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("X_fixed", "n_obs", n_obs);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("X_fixed", "n_fe + p * K",
        (n_fe + (p * K)));
      current_statement__ = 60;
      X_fixed_data__ = Eigen::Matrix<double,-1,-1>::Constant(n_obs, (n_fe +
                         (p * K)), std::numeric_limits<double>::quiet_NaN());
      new (&X_fixed)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_fixed_data__.data(), n_obs,
        (n_fe + (p * K)));
      current_statement__ = 60;
      stan::model::assign(X_fixed, stan::math::append_col(X, B),
        "assigning variable X_fixed");
      current_statement__ = 61;
      phi_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 61;
      phi_1dim__ = (p * K);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("phi", "p * K", phi_1dim__);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("phi", "p", p);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("beta", "n_fe", n_fe);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("beta", "p", p);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("z_u", "p", p);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("z_u", "J", J);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("z_u", "n_re", n_re);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("sd_u", "p", p);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("sd_u", "n_re", n_re);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("u", "p", p);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("u", "J", J);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("u", "n_re", n_re);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (phi_1dim__ * p) + (n_fe * p) + (p * (J * n_re)) + (p *
      n_re);
  }
  inline std::string model_name() const final {
    return "model_binary_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.37.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_binary_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto phi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(phi_1dim__,
          p);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_fe, p);
      current_statement__ = 3;
      auto z_u =
        in__.template read<
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(p, J, n_re);
      current_statement__ = 4;
      auto sd_u =
        in__.template read_constrain_lb<
          Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__, p,
          n_re);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> u =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(p,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, n_re,
            DUMMY_VAR__));
      current_statement__ = 7;
      for (int node = 1; node <= p; ++node) {
        current_statement__ = 6;
        stan::model::assign(u,
          stan::math::elt_multiply(
            stan::model::rvalue(z_u, "z_u", stan::model::index_uni(node)),
            stan::math::rep_matrix(
              stan::model::rvalue(sd_u, "sd_u", stan::model::index_uni(node),
                stan::model::index_omni()), J)), "assigning variable u",
          stan::model::index_uni(node));
      }
      {
        current_statement__ = 14;
        {
          stan::math::profile<local_scalar_t__> profile__("priors",
            const_cast<stan::math::profile_map&>(profiles__));
          current_statement__ = 8;
          lp_accum__.add(set_prior(stan::math::to_vector(beta),
                           prior_beta_fam, beta_loc, beta_scale, beta_df,
                           pstream__));
          current_statement__ = 9;
          lp_accum__.add(set_prior(stan::math::to_vector(phi), prior_phi_fam,
                           phi_loc, phi_scale, phi_df, pstream__));
          current_statement__ = 11;
          if (stan::math::logical_gt(n_re, 0)) {
            current_statement__ = 10;
            lp_accum__.add(set_half_prior(stan::math::to_vector(sd_u),
                             prior_sd_fam, sd_loc, sd_scale, sd_df, pstream__));
          }
          current_statement__ = 13;
          for (int node = 1; node <= p; ++node) {
            current_statement__ = 12;
            lp_accum__.add(stan::math::std_normal_lpdf<false>(
                             stan::math::to_vector(
                               stan::model::rvalue(z_u, "z_u",
                                 stan::model::index_uni(node)))));
          }
        }
        current_statement__ = 25;
        {
          stan::math::profile<local_scalar_t__> profile__("likelihood",
            const_cast<stan::math::profile_map&>(profiles__));
          current_statement__ = 24;
          for (int node = 1; node <= p; ++node) {
            current_statement__ = 15;
            stan::math::validate_non_negative_index("eta_re", "n_obs", n_obs);
            Eigen::Matrix<local_scalar_t__,-1,1> eta_re =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs,
                DUMMY_VAR__);
            current_statement__ = 17;
            stan::math::validate_non_negative_index("b_fixed",
              "n_fe + p * K", (n_fe + (p * K)));
            Eigen::Matrix<local_scalar_t__,-1,1> b_fixed =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant((n_fe + (p *
                K)), DUMMY_VAR__);
            current_statement__ = 19;
            stan::model::assign(eta_re,
              (stan::math::logical_gt(n_re, 0) ? stan::math::eval(
                                                   stan::math::rows_dot_product(
                                                     Z,
                                                     stan::model::rvalue(
                                                       stan::model::rvalue(u,
                                                         "u",
                                                         stan::model::index_uni(
                                                           node)), "u[node]",
                                                       stan::model::index_multi(
                                                         id),
                                                       stan::model::index_omni(
                                                         )))) : stan::math::eval(
                                                                  stan::math::promote_scalar<
                                                                    local_scalar_t__>(
                                                                    stan::math::rep_vector(
                                                                    0.0,
                                                                    n_obs)))),
              "assigning variable eta_re");
            current_statement__ = 20;
            stan::model::assign(b_fixed,
              stan::model::rvalue(beta, "beta", stan::model::index_omni(),
                stan::model::index_uni(node)), "assigning variable b_fixed",
              stan::model::index_min_max(1, n_fe));
            current_statement__ = 21;
            stan::model::assign(b_fixed,
              stan::model::rvalue(phi, "phi", stan::model::index_omni(),
                stan::model::index_uni(node)), "assigning variable b_fixed",
              stan::model::index_min_max((n_fe + 1), (n_fe + (p * K))));
            current_statement__ = 22;
            lp_accum__.add(stan::math::bernoulli_logit_glm_lpmf<false>(
                             stan::model::rvalue(Y, "Y",
                               stan::model::index_omni(),
                               stan::model::index_uni(node)), X_fixed,
                             eta_re, b_fixed));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_binary_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto phi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(phi_1dim__,
          p);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_fe, p);
      current_statement__ = 3;
      auto z_u =
        in__.template read<
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(p, J, n_re);
      current_statement__ = 4;
      auto sd_u =
        in__.template read_constrain_lb<
          Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__, p,
          n_re);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> u =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(p,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, n_re,
            DUMMY_VAR__));
      current_statement__ = 7;
      for (int node = 1; node <= p; ++node) {
        current_statement__ = 6;
        stan::model::assign(u,
          stan::math::elt_multiply(
            stan::model::rvalue(z_u, "z_u", stan::model::index_uni(node)),
            stan::math::rep_matrix(
              stan::model::rvalue(sd_u, "sd_u", stan::model::index_uni(node),
                stan::model::index_omni()), J)), "assigning variable u",
          stan::model::index_uni(node));
      }
      {
        current_statement__ = 14;
        {
          stan::math::profile<local_scalar_t__> profile__("priors",
            const_cast<stan::math::profile_map&>(profiles__));
          current_statement__ = 8;
          lp_accum__.add(set_prior(stan::math::to_vector(beta),
                           prior_beta_fam, beta_loc, beta_scale, beta_df,
                           pstream__));
          current_statement__ = 9;
          lp_accum__.add(set_prior(stan::math::to_vector(phi), prior_phi_fam,
                           phi_loc, phi_scale, phi_df, pstream__));
          current_statement__ = 11;
          if (stan::math::logical_gt(n_re, 0)) {
            current_statement__ = 10;
            lp_accum__.add(set_half_prior(stan::math::to_vector(sd_u),
                             prior_sd_fam, sd_loc, sd_scale, sd_df, pstream__));
          }
          current_statement__ = 13;
          for (int node = 1; node <= p; ++node) {
            current_statement__ = 12;
            lp_accum__.add(stan::math::std_normal_lpdf<false>(
                             stan::math::to_vector(
                               stan::model::rvalue(z_u, "z_u",
                                 stan::model::index_uni(node)))));
          }
        }
        current_statement__ = 25;
        {
          stan::math::profile<local_scalar_t__> profile__("likelihood",
            const_cast<stan::math::profile_map&>(profiles__));
          current_statement__ = 24;
          for (int node = 1; node <= p; ++node) {
            current_statement__ = 15;
            stan::math::validate_non_negative_index("eta_re", "n_obs", n_obs);
            Eigen::Matrix<local_scalar_t__,-1,1> eta_re =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs,
                DUMMY_VAR__);
            current_statement__ = 17;
            stan::math::validate_non_negative_index("b_fixed",
              "n_fe + p * K", (n_fe + (p * K)));
            Eigen::Matrix<local_scalar_t__,-1,1> b_fixed =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant((n_fe + (p *
                K)), DUMMY_VAR__);
            current_statement__ = 19;
            stan::model::assign(eta_re,
              (stan::math::logical_gt(n_re, 0) ? stan::math::eval(
                                                   stan::math::rows_dot_product(
                                                     Z,
                                                     stan::model::rvalue(
                                                       stan::model::rvalue(u,
                                                         "u",
                                                         stan::model::index_uni(
                                                           node)), "u[node]",
                                                       stan::model::index_multi(
                                                         id),
                                                       stan::model::index_omni(
                                                         )))) : stan::math::eval(
                                                                  stan::math::promote_scalar<
                                                                    local_scalar_t__>(
                                                                    stan::math::rep_vector(
                                                                    0.0,
                                                                    n_obs)))),
              "assigning variable eta_re");
            current_statement__ = 20;
            stan::model::assign(b_fixed,
              stan::model::rvalue(beta, "beta", stan::model::index_omni(),
                stan::model::index_uni(node)), "assigning variable b_fixed",
              stan::model::index_min_max(1, n_fe));
            current_statement__ = 21;
            stan::model::assign(b_fixed,
              stan::model::rvalue(phi, "phi", stan::model::index_omni(),
                stan::model::index_uni(node)), "assigning variable b_fixed",
              stan::model::index_min_max((n_fe + 1), (n_fe + (p * K))));
            current_statement__ = 22;
            lp_accum__.add(stan::math::bernoulli_logit_glm_lpmf<false>(
                             stan::model::rvalue(Y, "Y",
                               stan::model::index_omni(),
                               stan::model::index_uni(node)), X_fixed,
                             eta_re, b_fixed));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_binary_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto phi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(phi_1dim__,
          p);
      current_statement__ = 2;
      auto beta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_fe, p);
      current_statement__ = 3;
      auto z_u =
        in__.template read<
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(p, J, n_re);
      current_statement__ = 4;
      auto sd_u =
        in__.template read_constrain_lb<
          Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__, p,
          n_re);
      std::vector<Eigen::Matrix<double,-1,-1>> u =
        std::vector<Eigen::Matrix<double,-1,-1>>(p,
          Eigen::Matrix<double,-1,-1>::Constant(J, n_re,
            std::numeric_limits<double>::quiet_NaN()));
      out__.write(phi);
      out__.write(beta);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
            out__.write(stan::model::rvalue(z_u, "z_u",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      out__.write(sd_u);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 7;
      for (int node = 1; node <= p; ++node) {
        current_statement__ = 6;
        stan::model::assign(u,
          stan::math::elt_multiply(
            stan::model::rvalue(z_u, "z_u", stan::model::index_uni(node)),
            stan::math::rep_matrix(
              stan::model::rvalue(sd_u, "sd_u", stan::model::index_uni(node),
                stan::model::index_omni()), J)), "assigning variable u",
          stan::model::index_uni(node));
      }
      if (emit_transformed_parameters__) {
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
              out__.write(stan::model::rvalue(u, "u",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> phi =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(phi_1dim__, p,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(phi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(phi_1dim__, p),
        "assigning variable phi");
      out__.write(phi);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_fe, p, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n_fe, p),
        "assigning variable beta");
      out__.write(beta);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> z_u =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(p,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, n_re,
            DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
            current_statement__ = 3;
            stan::model::assign(z_u, in__.read<local_scalar_t__>(),
              "assigning variable z_u", stan::model::index_uni(sym3__),
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(z_u);
      Eigen::Matrix<local_scalar_t__,-1,-1> sd_u =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(p, n_re, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(sd_u,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(p, n_re),
        "assigning variable sd_u");
      out__.write_free_lb(0, sd_u);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "phi", "double",
        std::vector<size_t>{static_cast<size_t>(phi_1dim__),
          static_cast<size_t>(p)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(n_fe),
          static_cast<size_t>(p)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "z_u", "double",
        std::vector<size_t>{static_cast<size_t>(p), static_cast<size_t>(J),
          static_cast<size_t>(n_re)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sd_u", "double",
        std::vector<size_t>{static_cast<size_t>(p),
          static_cast<size_t>(n_re)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> phi =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(phi_1dim__, p,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> phi_flat__;
        current_statement__ = 1;
        phi_flat__ = context__.vals_r("phi");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= phi_1dim__; ++sym2__) {
            stan::model::assign(phi, phi_flat__[(pos__ - 1)],
              "assigning variable phi", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(phi);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_fe, p, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_fe; ++sym2__) {
            stan::model::assign(beta, beta_flat__[(pos__ - 1)],
              "assigning variable beta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> z_u =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(p,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, n_re,
            DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> z_u_flat__;
        current_statement__ = 3;
        z_u_flat__ = context__.vals_r("z_u");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
              stan::model::assign(z_u, z_u_flat__[(pos__ - 1)],
                "assigning variable z_u", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(z_u);
      Eigen::Matrix<local_scalar_t__,-1,-1> sd_u =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(p, n_re, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sd_u_flat__;
        current_statement__ = 4;
        sd_u_flat__ = context__.vals_r("sd_u");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= p; ++sym2__) {
            stan::model::assign(sd_u, sd_u_flat__[(pos__ - 1)],
              "assigning variable sd_u", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lb(0, sd_u);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"phi", "beta", "z_u", "sd_u"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"u"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    phi_1dim__),
                                                 static_cast<size_t>(p)},
                std::vector<size_t>{static_cast<size_t>(n_fe),
                  static_cast<size_t>(p)},
                std::vector<size_t>{static_cast<size_t>(p),
                  static_cast<size_t>(J), static_cast<size_t>(n_re)},
                std::vector<size_t>{static_cast<size_t>(p),
                  static_cast<size_t>(n_re)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(p),
               static_cast<size_t>(J), static_cast<size_t>(n_re)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= phi_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n_fe; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
          param_names__.emplace_back(std::string() + "z_u" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= p; ++sym2__) {
        param_names__.emplace_back(std::string() + "sd_u" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
            param_names__.emplace_back(std::string() + "u" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= phi_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n_fe; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
          param_names__.emplace_back(std::string() + "z_u" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= p; ++sym2__) {
        param_names__.emplace_back(std::string() + "sd_u" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_re; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= p; ++sym3__) {
            param_names__.emplace_back(std::string() + "u" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"phi\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(phi_1dim__) + ",\"cols\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_fe) + ",\"cols\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"z_u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(n_re) + "}},\"block\":\"parameters\"},{\"name\":\"sd_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p) + ",\"cols\":" + std::to_string(n_re) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(n_re) + "}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"phi\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(phi_1dim__) + ",\"cols\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_fe) + ",\"cols\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"z_u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(n_re) + "}},\"block\":\"parameters\"},{\"name\":\"sd_u\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p) + ",\"cols\":" + std::to_string(n_re) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(n_re) + "}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((phi_1dim__ * p) + (n_fe * p)) + (p * (J *
      n_re))) + (p * n_re));
    const size_t num_transformed = emit_transformed_parameters * ((p * (J *
      n_re)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((phi_1dim__ * p) + (n_fe * p)) + (p * (J *
      n_re))) + (p * n_re));
    const size_t num_transformed = emit_transformed_parameters * ((p * (J *
      n_re)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_binary_model_namespace::model_binary_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_binary_model_namespace::profiles__;
}
#endif